intermediary-auditor: shipping first version
letsencrypt/sre-tools pull request #26
Opened 2020-12-02 22:31 UTC by beautifulentropy

For a given list of hostnames, this tool dials and starts a TLS
handshake and audits the (raw) Cetificate Chain presented for
inconsistencies between the Issuer Subject Name of the leaf certificate
and the Subject Name of the of the intermediary certificate.

Accepting inputs are, space separated hostnames supplied via stdin or a
path to a csv file provided following the --stats-csv-file flag. The csv
file must contain the hostname in the first column of every row and must
be in the following format <tld label> followed by each <label> of the
hostname in reverse order (i.e. mail.google.com would be
com.google.mail)

Provided also is a debug mode. If the operator supplies the flag --debug
all hostnames audited will have their results printed in the following
format: leafCert: [subjectCN: <subjectCN> | issuerCN: <issuerCN>] ->
chainCert0: [subjectCN: <subjectCN> | issuerCN: <issuerCN>]

2020-12-02 22:34 UTC, beautifulentropy commented
Trying to balance getting this out in a timeline where we can derive value from it today and overall quality. To that end there are two things to note:
- At present there are no tests, I am going to work on them and submit in another PR if that's fine
- My concurrency is borked and while all of the output is showing up just fine the script needs to be halted using `ctrl+c`

2020-12-02 22:48 UTC, jsha requested changes

2020-12-02 22:48 UTC, jsha commented on cmd/intermediary-auditor/main.go
> +var debugMode bool
For global flags, you can do:

```
var debugMode = flag.Bool(....)
```

2020-12-02 22:48 UTC, jsha commented on cmd/intermediary-auditor/main.go
> +	}
You should move the WaitGroup into this scope. Also I think what you want concurrency-wise is more like this:

```
var wg sync.WaitGroup
for i := 0; i < 10; i++ {
  wg.Add(1)
  go func(hostname) {
    for hostname := range c {
      auditHostname(hostname)
    }
    wg.Done()
  }(hostname)
  wg.Wait()
}
```

2020-12-02 22:48 UTC, jsha commented on cmd/intermediary-auditor/main.go
> +	close(c)
This `close()` should move up to line 182, right after the for loop that writes hostnames to the channels. Close signals to consumers "no more values to come".

2020-12-02 22:54 UTC, aarongable commented on cmd/intermediary-auditor/main.go
> +var statsCsv string
It makes sense to have debugMode as a global here, but because statsCsv should be (and is in the current implementation) passed around as an argument, there's no need to predeclare it here. Just declare it on line 162, and use `flag.Str` instead of `flag.StrVar`.

2020-12-02 22:54 UTC, aarongable commented on cmd/intermediary-auditor/main.go
> +	defer wg.Done()
It would be more idiomatic for auditHostname to take a reference to the waitgroup as an argument, rather than having it as a global.

2020-12-02 22:54 UTC, aarongable commented on cmd/intermediary-auditor/main.go
> +	flag.StringVar(&statsCsv, "stats-csv-file", "", "path to csv file produced by stats-exporter")
This says "stats-csv-file", but the usage text on line 173 says "stats-exporter-file"

2020-12-02 22:54 UTC, aarongable commented on cmd/intermediary-auditor/main.go
> +func statsCsvToHostnames(statsCsv string) []string {
Is CSV correct? I thought that the format of the files dumped by stats-exporter was compressed tab-separated-values, not comma-separated (which you can get Go's `csv.NewReader` to read anyway using `r.comma = '\t'`). Does this work anyway?

2020-12-02 22:54 UTC, aarongable commented on cmd/intermediary-auditor/main.go
> +				fmt.Println(misconfiguredCertCN)
Ideally, `auditHostname` would return (or write to a channel) a result value, rather than printing it directly. Having each goroutine print directly leads to the possibility of multiple goroutines printing simultaneously, resulting in interleaved output.

Since this `VerifyPeerCertificate` function is a closure, you can have it write directly to a boolean owned by `auditHostname` in order to exfiltrate the audit result that way.

2020-12-02 22:54 UTC, jsha requested changes

2020-12-02 22:54 UTC, jsha commented on cmd/intermediary-auditor/main.go
> +		if leafIssuerCN == x3 && chainContainsX3(chain) {
I think for this line we should just say `if leafIssuerCN == x3`. The reasoning is this: We want this script to catch _new_ problems only. Plenty of people have the problem that they're deploying an X3-signed leaf without a chain. We don't care about those cases for this particular task. We may later want to adapt this to catch that category of cases, though.

```suggestion
		if leafIssuerCN == x3 {
```

2020-12-02 22:54 UTC, jsha commented on cmd/intermediary-auditor/main.go
> +// The tls.Config skips verification steps and delegates verfication to
```suggestion
// The tls.Config skips verification steps and delegates verification to
```

2020-12-02 22:58 UTC, jsha commented on cmd/intermediary-auditor/main.go
> +				fmt.Println(misconfiguredCertCN)
This is a good point about interleaving. I had thought stdout was safe here, but on looking again it's not: https://stackoverflow.com/questions/14694088/is-it-safe-for-more-than-one-goroutine-to-print-to-stdout.

That said, I think having an output channel adds a lot of complexity and challenges. As a quick fix, what do you think of having a global mutex that we take before each print?

2020-12-02 23:16 UTC, beautifulentropy commented on cmd/intermediary-auditor/main.go
> +func statsCsvToHostnames(statsCsv string) []string {
You are correct! I had somehow internalized that as CSV instead of TSV.

2020-12-02 23:19 UTC, beautifulentropy commented on cmd/intermediary-auditor/main.go
> +var statsCsv string
Alright, I've gone ahead and moved it down to main, I still need to declare it before assignment, otherwise the compiler will complain, so I'm still doing a flag.StringVar

2020-12-03 00:27 UTC, beautifulentropy commented on cmd/intermediary-auditor/main.go
> +func statsCsvToHostnames(statsCsv string) []string {
Your suggested fix also worked, thank you.

2020-12-03 00:29 UTC, beautifulentropy commented on cmd/intermediary-auditor/main.go
> +				fmt.Println(misconfiguredCertCN)
Addressed this by using a total of three channels, one for hostnames to be consumed by goroutines, one for results to be sent and printed, and one to hold open until all results have been printed.

2020-12-03 00:33 UTC, beautifulentropy commented on cmd/intermediary-auditor/main.go
> +		if leafIssuerCN == x3 && chainContainsX3(chain) {
Awesome, and this drastically simplifies the function.

2020-12-03 00:42 UTC, jsha commented
One piece of input I forgot to give in the first round: Let's call this chain-auditor or (less preferred) intermediate-auditor. An intermediary is someone who acts as a go-between. In my mind it's most associated with section 230 and "intermediary liability:" https://www.internetsociety.org/blog/2020/03/intermediary-liability-the-hidden-gem/

2020-12-03 00:47 UTC, beautifulentropy commented
> One piece of input I forgot to give in the first round: Let's call this chain-auditor or (less preferred) intermediate-auditor. An intermediary is someone who acts as a go-between. In my mind it's most associated with section 230 and "intermediary liability:" https://www.internetsociety.org/blog/2020/03/intermediary-liability-the-hidden-gem/

I have one more round of changes I need to make, so I'll do it before pushing.

2020-12-03 00:49 UTC, jsha requested changes

2020-12-03 00:49 UTC, jsha commented on cmd/intermediary-auditor/main.go
> +// chaing2String is used solely if debug is true. Iterates from the
```suggestion
// chain2String is used solely if debug is true. Iterates from the
```

2020-12-03 00:49 UTC, jsha commented on cmd/intermediary-auditor/main.go
> +func chaing2String(chain []*x509.Certificate) string {
```suggestion
func chain2String(chain []*x509.Certificate) string {
```

2020-12-03 00:49 UTC, jsha commented on cmd/intermediary-auditor/main.go
> +			fmt.Println(chaing2String(chain))
```suggestion
			fmt.Println(chain2String(chain))
```

2020-12-03 01:17 UTC, jsha requested changes

2020-12-03 01:17 UTC, jsha commented on cmd/chain-auditor/main.go
> +			return chain[0].Subject.CommonName
The name that happened to get promoted to CommonName may not be the same one we were auditing. I think we should change this function to return `error`, and `auditHostname` should check for error and print the input hostname if it was non-nil.

2020-12-03 01:22 UTC, beautifulentropy commented on cmd/chain-auditor/main.go
> +			return chain[0].Subject.CommonName
Oh, yes, this totally makes sense

2020-12-03 01:46 UTC, jsha approved these changes

2020-12-03 04:53 UTC, aarongable approved these changes
Two optional nits, but feel free to submit!

2020-12-03 04:53 UTC, aarongable commented on cmd/chain-auditor/main.go
> +func auditChain(rawCerts [][]byte) string {
nit: since `auditHostname` only cares whether the string returned by this is the empty string, this could be a boolean method instead.

2020-12-03 04:53 UTC, aarongable commented on cmd/chain-auditor/main.go
> +		fmt.Print("You must supply at least one hostname via stdin or tsv file using `--stats-tsv-file`")
technically "...hostname via the command line or..."; reading from stdin would mean reading lines from `os.Stdin`, rather than `os.Args`.

2020-12-03 20:02 UTC, beautifulentropy commented on cmd/chain-auditor/main.go
> +		fmt.Print("You must supply at least one hostname via stdin or tsv file using `--stats-tsv-file`")
This is correct. Thanks for pointing it out.

2020-12-03 20:02 UTC, beautifulentropy commented on cmd/chain-auditor/main.go
> +func auditChain(rawCerts [][]byte) string {
Excellent, I've gone ahead and made the appropriate changes.

2020-12-03 20:16 UTC, jsha commented on cmd/chain-auditor/main.go
> +// mistmatchInChain for a given slice of byte slices representing an
```suggestion
// mismatchInChain for a given slice of byte slices representing an
```

2020-12-03 23:44 UTC, beautifulentropy commented on cmd/chain-auditor/main.go
> +// mistmatchInChain for a given slice of byte slices representing an
oh gosh, thanks.

2020-12-04 00:23 UTC, jsha approved these changes

2020-12-04 06:31 UTC, merged