Feature Update to Chain Auditor
letsencrypt/sre-tools pull request #28
Opened 2020-12-15 22:24 UTC by beautifulentropy

Outputs to a TSV file instead of stdout. Added a flag to adjust
parallelism. Added a progress bar that tracks: percent complete, rate of
completion, remaining count, and errors by count. Refactored the result
returned to a struct containing the info needed for the progress bar and
(later) Prometheus stats. Added all of the logic to populate everything
but the agent version in the result struct. Removed ChainToString.

2020-12-21 22:48 UTC, aarongable requested changes

2020-12-21 22:48 UTC, aarongable commented on cmd/chain-auditor/main.go
> +func getConnectProbs(err error) probs {
This isn't important, but an idea: define an `.Error()` method on the probs struct, so it satisfies the `error` interface, and then store the underlying error in the struct as well. That way code which receives an "empty" probs struct (i.e. the underlying code got an error but it wasn't _any_ of the three cases handled here) still has something to work with.

2020-12-21 22:48 UTC, aarongable commented on cmd/chain-auditor/main.go
> +			conn.RemoteAddr().String(), ":443", "")).String()
It might be better to find the location of a ":" in the string, and then `ParseIP` the string indexed up to that point. Just for resilience in the case of weird port shenanigans.

2020-12-21 22:48 UTC, aarongable commented on cmd/chain-auditor/main.go
> +	result := result{hostname: hostname}
A thing you could do is initialize `result` all the way up on line 127 and then set `result.mismatched = ...` on line 132. It removes the duplication from lines 140 and 144.

2020-12-21 22:48 UTC, aarongable commented on cmd/chain-auditor/main.go
> +		// line reduces our hostnames list by ~10%
Rather than reducing our search space, we _could_ instead choose to dial "example.com" (without the wildcard). This won't always work, as some sites don't host anything outside of subdomains. Thoughts on the tradeoff?

2020-12-21 22:48 UTC, aarongable commented on cmd/chain-auditor/main.go
> +func parseCLIOptions() (*string, *int) {
Since you have a helper function for this anyway, dereference the flag vars and just return `(string, int)` so you don't have to be dereferencing on lines 212, 214, 236, 237, and 265.

2020-12-21 22:48 UTC, aarongable commented on cmd/chain-auditor/main.go
> +	var mismatchedCount int
I look forward to the day that these counts are replaced with prometheus counters :D

2020-12-21 22:48 UTC, aarongable commented on cmd/chain-auditor/main.go
> +	_, err = auditFile.Write([]byte(
Consider having this summary be written to a different file. Maybe every individual run writes its results to a run-specific file, and then writes its one-line summary to a file shared across runs. That way each file can be CSV (or TSV) parseable on its own, without having to worry about two different data formats on different lines of the same file.

2020-12-21 22:48 UTC, aarongable commented on cmd/chain-auditor/daily-work.sh
> +# Move the finished audit log to a folder with all of it's friends, also makes
```suggestion
# Move the finished audit log to a folder with all of its friends, also makes
```

2020-12-21 23:15 UTC, beautifulentropy commented on cmd/chain-auditor/main.go
> +func getConnectProbs(err error) probs {
The udea us a good one, but at the moment I don't plan to do anything with errors. Given that about 60,000 of these fall under netOther I'm not sure logging them makes much sense.

2020-12-21 23:21 UTC, beautifulentropy commented on cmd/chain-auditor/main.go
> +			conn.RemoteAddr().String(), ":443", "")).String()
The TLS dialer is hard coded to dial on 443, so it should always be 443, right? Adding to that, if we have an IPV6 IP, those would be full of `:`

2020-12-21 23:25 UTC, beautifulentropy commented on cmd/chain-auditor/main.go
> +		// line reduces our hostnames list by ~10%
My inclination is to only scan hostnames that we know, for a fact, we issued for during a given day.

2020-12-21 23:32 UTC, jsha requested changes

2020-12-21 23:32 UTC, jsha commented on cmd/chain-auditor/daily-work.sh
> +./chain-auditor --stats-tsv-file "${UNPACKED_STATS_FILENAME}" --parallelism 150
I don't think this needs to change, but a nice trick for the future: You can do:

```
./chain-auditor --stats-tsv-file <(zcat ${MOUNT_POINT}/${STATS_FILENAME}) --parallelism 150
```

To avoid having to unpack into a temp file. This acts a lot like a pipe - Bash will create an FD, sub it in for that argument, and hook that FD up to the stdout of the command inside `<(....)`. You can also of course do a similar thing in a more familiar way by having `chain-auditor` take input on stdin and doing `zcat foo | chain-auditor`.

2020-12-21 23:32 UTC, jsha commented on cmd/chain-auditor/main.go
> +// Timeout, or Network Other
Technically this is taking the output of a TLS dial (which includes a TCP dial, but can have more errors). Also I'd remove the `of port 443`, since there's nothing in this function that's specific to that port.

2020-12-21 23:32 UTC, jsha commented on cmd/chain-auditor/main.go
> +			conn.RemoteAddr().String(), ":443", "")).String()
We have SplitHostPort for this: https://golang.org/pkg/net/#SplitHostPort

2020-12-21 23:32 UTC, jsha commented on cmd/chain-auditor/main.go
> +func parseTLSVersionFromConn(conn *tls.Conn) string {
Nit: This isn't parsing a TLS version. I would just call this `tlsVersionFromConn`.

2020-12-21 23:32 UTC, jsha commented on cmd/chain-auditor/main.go
> +func setupProgressBar(total int) *bar.Bar {
FYI, you can do a progress bar on the cheap (without taking dependencies) by printing the status using min-width formats (e.g. `%20d`, `%20s` etc), and printing `\r` at the end of each line rather than `\n`. I don't think you need to rewrite this but figure you might enjoy the trick! If this were in Boulder I would want to invest more effort in avoiding the dependency.

2020-12-21 23:32 UTC, jsha commented on cmd/chain-auditor/main.go
> +// same origin
I would say "IP address" here. Origin has a couple of different meanings:

 1. The backend for a reverse proxy or CDN.
 2. The (scheme, hostname, port) tuple used by the Same-Origin Policy in web security.
 
 Neither applies here. Our concern is that two different origins (in this case, two different hostnames, since scheme and port are constant) resolve to the same IP address, and that origins resolving to the same IP address are more likely than average to be adjacent in our input files.

2020-12-21 23:32 UTC, jsha commented on cmd/chain-auditor/main.go
> +		// line reduces our hostnames list by ~10%
If `example.com` was on the certificate, it will also show up as its own hostname, since `*.example.com` doesn't match `example.com`. We could try a random subdomain like `foo.example.com`, but I think it's sufficient to just drop these. Most certificate with wildcards will also have at least one plain FQDN.

2020-12-21 23:32 UTC, jsha commented on cmd/chain-auditor/main.go
> +		fmt.Print("You must supply at least one hostname as an argument or a file of using `--stats-tsv-file`")
```suggestion
		fmt.Print("You must supply a file containing at least one hostname using `--stats-tsv-file`")
```

2020-12-21 23:38 UTC, beautifulentropy commented on cmd/chain-auditor/main.go
> +			conn.RemoteAddr().String(), ":443", "")).String()
> We have SplitHostPort for this: https://golang.org/pkg/net/#SplitHostPort

Ah perfect, thank you

2020-12-21 23:40 UTC, jsha requested changes

2020-12-21 23:40 UTC, jsha commented on cmd/chain-auditor/main.go
> +	auditFile, err := os.OpenFile(fileName, os.O_CREATE|os.O_CREATE|os.O_WRONLY, 0644)
Duplicated flag:

```suggestion
	auditFile, err := os.OpenFile(fileName, os.O_CREATE|os.O_WRONLY, 0644)
```

2020-12-21 23:40 UTC, jsha commented on cmd/chain-auditor/main.go
> +				if result.mismatched == true {
For booleans, it's more idiomatic in Go to just say `if result.mismatched`. Same feedback on the line below, and on line 278 (`if !result.reachable {`).

Also, a style point: on line 277, you have `hostnamesRemainCount--`, a single line squashed between two `if` statements. I'd like that to be either at the bottom or the top of this group of `if` statements. I think the top makes the most sense. Maybe even the top of the `for` loop?

2020-12-21 23:40 UTC, jsha commented on cmd/chain-auditor/main.go
> +			_, err := auditFile.Write([]byte(fmt.Sprintf("%s\t%s\n", result.hostname, result.ip)))
I would do this with `fmt.Fprintf`:

```suggestion
			err := fmt.Fprintf(auditFile, "%s\t%s\n", result.hostname, result.ip)
```

2020-12-22 00:25 UTC, beautifulentropy commented on cmd/chain-auditor/main.go
> +				if result.mismatched == true {
This is super nice to hear! I had always wanted to do the same in Python but there's the whole explicit over implicit rule in Python.

2020-12-22 00:32 UTC, beautifulentropy commented on cmd/chain-auditor/main.go
> +		fmt.Print("You must supply at least one hostname as an argument or a file of using `--stats-tsv-file`")
Ah, thanks, I forgot that I removed os.Args input

2020-12-22 00:43 UTC, beautifulentropy commented on cmd/chain-auditor/main.go
> +// same origin
Thanks for explaining this! I can definitely see how my original wording would have conveyed the incorrect message.

2020-12-22 00:57 UTC, beautifulentropy commented on cmd/chain-auditor/main.go
> +			_, err := auditFile.Write([]byte(fmt.Sprintf("%s\t%s\n", result.hostname, result.ip)))
🤦🏻 yeah, this is a lot cleaner too

2020-12-22 01:03 UTC, beautifulentropy commented on cmd/chain-auditor/daily-work.sh
> +./chain-auditor --stats-tsv-file "${UNPACKED_STATS_FILENAME}" --parallelism 150
This is pretty fun! I think I'm going to pass on it for now, but I will keep it in mind.

2020-12-22 02:49 UTC, jsha requested changes

2020-12-22 02:49 UTC, jsha commented on cmd/chain-auditor/main.go
> +var tlsVersions = map[uint16]string{
I think this can be a `const`.

2020-12-22 02:49 UTC, jsha commented on cmd/chain-auditor/main.go
> +// shuffleHostnames Our input files contain many adjacent hostnames
godoc style asks that the function name be first in the comment so it can always act as the subject of the sentence, e.g. "shuffleHostnames randomizes the order of the hostnames it was passed. Our input files contain ..".

Also, since `rand.Shuffle` shuffles in place, there's no need to return a value. You just need to specify that the input is modified.

2020-12-22 02:49 UTC, jsha commented on cmd/chain-auditor/main.go
> +// getConnectProbs for a given error resulting from an attempt to TLS
This should be a sentence with the subject `getConnectProbs`.

2021-01-04 20:05 UTC, beautifulentropy commented on cmd/chain-auditor/main.go
> +var tlsVersions = map[uint16]string{
Sadly, the Go compiler doesn't support map constants.

2021-01-04 20:06 UTC, beautifulentropy commented on cmd/chain-auditor/main.go
> +// shuffleHostnames Our input files contain many adjacent hostnames
Ooh, thanks, I had totally forgotten about this!

2021-01-04 22:53 UTC, beautifulentropy commented on cmd/chain-auditor/main.go
> +// shuffleHostnames Our input files contain many adjacent hostnames
>Also, since rand.Shuffle shuffles in place, there's no need to return a value. You just need to specify that the input is modified.

I might be missing something, but given it's current form I believe I still need to return a value.

2021-01-05 02:22 UTC, jsha commented on cmd/chain-auditor/main.go
> +// shuffleHostnames Our input files contain many adjacent hostnames
I don't think you need to return a value. The input slice `hostnames []string` is modified in place. Under the hood, a slice is essentially a pointer to memory somewhere else. By passing a slice, the caller of `shuffleHostnames` is allowing `shuffleHostnames` to modify that slice.

2021-01-05 18:23 UTC, beautifulentropy commented on cmd/chain-auditor/main.go
> +// shuffleHostnames Our input files contain many adjacent hostnames
In it's current form `shuffleHostnames` is called as the return value of another function, which is where I believe I got a bit confused. If I just refactor that to a call to `shuffleHostnames` and then return hostnames from that same func then it will work.

2021-01-05 20:15 UTC, aarongable approved these changes

2021-01-05 20:38 UTC, jsha approved these changes

2021-01-05 21:46 UTC, merged