Add S3 file drop utility
letsencrypt/sre-tools pull request #31
Opened 2021-05-11 20:35 UTC by beautifulentropy

Add utility with the following functionality
- Configuration provided in a YAML file
- List contents of an S3 bucket
- Upload a single file to an S3 bucket
- Delete a single file from an S3 bucket

2021-05-11 23:40 UTC, tgeoghegan commented
I haven't reviewed this in detail, but it seems like everything this tool does is already supported by [the AWS CLI tool](https://aws.amazon.com/cli/). Do we need to maintain our own in-house clone of `aws s3 [ls cp rm]`?

2021-05-12 00:01 UTC, jkarner commented
>  Do we need to maintain our own in-house clone of `aws s3 [ls cp rm]`?

At the moment, it would be overkill to install and maintain the asw-cli tool in the secure DC environment when we only need a small set of functions.

2021-05-12 00:09 UTC, jsha commented
I definitely support minimizing the amount of code and dependencies we pull in, but this PR does wind up pulling in the AWS Go SDK, which I think is roughly equivalent in size to the aws cli tool (which IIRC uses the AWS Python SDK, "boto"). What is the work involved in maintaining the aws-cli tool in prod? Does it have nonstandard / difficult install and update pathways?

2021-05-12 00:35 UTC, beautifulentropy commented
I'll be the first to admit that I honestly didn't think about the issue of vendoring the SDK. If folks want me to investigate other avenues, such as interacting with the S3 API using the net/http package, I'm more than happy to do so ☺️.

2021-05-12 00:58 UTC, jsha requested changes

2021-05-12 00:58 UTC, jsha commented on cmd/s3-file-upload/main.go
> +	BucketName      string `yaml:"bucket_name"`
Generally we separate secrets from config - for instance the main config would contain a path to a file where it can read the secrets.

However, since this config is so small, we could probably put the whole thing in the secrets repo.

2021-05-12 00:58 UTC, jsha commented on cmd/s3-file-upload/main.go
> +	awsConfig, err := config.LoadDefaultConfig(context.TODO())
Let's make this a `context.Background`. We don't intend to put in a different context here at some point.

2021-05-12 00:58 UTC, jsha commented on cmd/s3-file-upload/main.go
> +		c.AccessKeyID, c.SecretAccessKey, "")
Why prefer the static credentials over the SDK's default system of searching for them on disk, in the env, etc?

2021-05-12 21:04 UTC, beautifulentropy commented on cmd/s3-file-upload/main.go
> +	BucketName      string `yaml:"bucket_name"`
Is there any action I need to take here?

2021-05-12 21:19 UTC, beautifulentropy commented on cmd/s3-file-upload/main.go
> +		c.AccessKeyID, c.SecretAccessKey, "")
I'm not accustomed to keeping credentials on disk in production environments. So this was more a matter of what are we already accustomed to templating on disk. The answer I got for that was JSON and YAML. Since AWS configuration files are INI I went with a YAML loader.

That being said, I'm not particularly attached to this solution. I would prefer that credentials like these are eventually loaded from a secret store. To that end, this code snippet would be easier to modify than switching from the credential discovery mechanism that the the package defaults to.

2021-05-17 22:57 UTC, jsha commented on cmd/s3-file-upload/main.go
> +	BucketName      string `yaml:"bucket_name"`
Nope. Just make sure SRE treats the whole config as a secret when they deploy it.

2021-05-18 00:35 UTC, jsha approved these changes

2021-05-20 21:18 UTC, merged