State based DNS system that fits our needs
letsencrypt/sre-tools pull request #38
Opened 2021-08-13 21:05 UTC by aaomidi

What this doesn't do (yet?)

- If a dns record with the same `name` and `conten`t exists, but the ttl/proxy/etc/etc is different, this is going to assume a DNS record doesn't exist and fail in creating one. Easy to solve, and can address this later if we think its important.
- Nice error messages telling you what is missing in your environment when running this. If you don't pass in a toml right now it freaks out and quits.

2021-10-20 02:19 UTC, jsha reviewed
Nice work! This will be an excellent tool. Thanks for working on it.

2021-10-20 02:19 UTC, jsha commented on cmd/cloudflare-dns-handler/cloudflare/create.go
> +type DNSRecord struct {
This seems vestigial? Replace with `type Record struct`

2021-10-20 02:19 UTC, jsha commented on cmd/cloudflare-dns-handler/cloudflare/main.go
> +			return &record
Since `Record` contains only types for which `==` is defined, I think you can just use `record == want` here.

2021-10-20 02:19 UTC, jsha commented on cmd/cloudflare-dns-handler/cloudflare/main.go
> +	if res.StatusCode >= 500 {
Also check for 4xx? And you should wrap the errors such that the method and URL are included in the error message.

2021-10-20 02:19 UTC, jsha commented on cmd/cloudflare-dns-handler/main.go
> +	path := path.Join(homeDir, ".config", "cloudflare-dns-handler", "api_token")
This path should come from a command line flag, environment variable, or the configuration file.

2021-10-20 02:19 UTC, jsha commented on cmd/cloudflare-dns-handler/cloudflare/main.go
> +func (c *cloudflare) Apply(conf config.Configuration) error {
This method applies all the changes as it finds them. Instead, it should build a list of changes that need to happen, and then apply them as a separate step. That will allow you to add a dry run mode that shows what _would_ happen if it proceeded.

That would also help you eliminate some of the noisy logging of "Checking if ..."; "Record exists"; "Record does not exist". That would all be summarized by logging a set of planned changes (and maybe also logging the existing and planned states of the zone, to help debug the tool itself).

2021-10-20 02:19 UTC, jsha commented on cmd/cloudflare-dns-handler/cloudflare/main.go
> +		fmt.Printf("Checking if %s with value of %s exists\n", record.Name, record.Content)
Maybe use the `log` package for these and get automatic timestamping? Although if this output will mainly go to syslog, I guess that will add timestamps. That adds another thought - perhaps this should be designed to automatically log to syslog, since these will be important config changes that we want a record of.

2021-10-20 02:19 UTC, jsha commented on cmd/cloudflare-dns-handler/cloudflare/main.go
> +		if record.Exist { // We want the record to exist
It's a bit odd that you need to explicitly list all the records you want to not-exist. Wouldn't it be better to say "any record not listed in the config file should not-exist?"

2021-10-20 02:19 UTC, jsha commented on cmd/cloudflare-dns-handler/cloudflare/main.go
> +					log.Fatalf("\tError when creating the DNS record: %v\n", err)
I think it would be better to combine this with the return, and let the caller print the error:

`return fmt.Errorf("creating dns record %s %s in %s: %w", record.Type, record.Name, conf.ZoneIdentifier, err)`

2021-10-20 02:19 UTC, jsha commented on cmd/cloudflare-dns-handler/cloudflare/main.go
> +				continue
This continue is redundant because of the nested if/elses.

By the way I bet you could clean up the structure something like this:

```
if record.Exist && result == nil {
  // add it
} else if !record.Exist && result != nil {
  // delete it
}
```

2021-10-20 02:19 UTC, jsha commented on cmd/cloudflare-dns-handler/cloudflare/main.go
> +				err = c.handleDeletion(conf.ZoneIdentifier, result)
Let's make sure when we delete something, we log the previous contents. Probably that's taken care of by my suggestion above to log the before and planned states.

2021-10-20 02:19 UTC, jsha commented on cmd/cloudflare-dns-handler/cloudflare/main.go
> +		return result, fmt.Errorf("%w: %v", FailedToParseGeneralResponseErr, err)
Why %v for the err here? %s is generally better.

2021-10-20 02:44 UTC, jsha commented
A couple more things: When you build the list of changes, there should actually be three categories of planned change: create, delete, and modify. Performing a modify will wind up actually being a delete and a create, but I think it's useful to present it to the user as its own category of change, since it's easier to reason about.

Also, the title of the PR is "State based DNS system that fits our needs." Can you update the PR description to describe what the needs are?

2021-10-22 03:07 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/main.go
> +			return &record
I think I did this because I wanted to ignore the `exist` value.

2021-10-27 22:40 UTC, jsha submitted a review, later dismissed
Ok, done reviewing. One note: You mentioned terraform isn't a good fit for this use case because you want to use this to maintain "mixed" zones where some records are under management by this tool, and some are not. I see the starting zones are our OCSP zones, which I would have thought only had A records from them. What are the other records in those zones?

Also, I note your starting configurations have `zone_identifier = "we will have to get this from an API call"`, which suggests that before running this for a zone, you have to get a zone identifier, which seems like toil - and is also an opportunity for error. I know in Route 53 there is a way to enumerate zones and figure out which zone ID corresponds to a given domain name. Can we do that with Cloudflare's API? It would be much nicer to say at the top `zone = prod-ocsp.letsencrypt.org` and let the tool do the necessary lookups to find the corresponding zone ID.

2021-11-02 16:23 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/cloudflare.go
> +	"text/tabwriter"
Oh yeah I actually stopped using this and forgot to remove it from the struct.

2021-11-02 16:25 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/action.go
> +	return strings.Join(a.TableDisplay(), " ")
This is meant for syslog logging, and I think it looked fine when I checked.

2021-11-02 16:27 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/cloudflare.go
> +			}
This is a bit confusing and I'll try to add some comments to describe whats happening. We're basically looping over our desired file somewhere outside of this function (Specifically in `DiffState`) and then we look at the existing records and see what record (there will only be one) to remove/add/modify to make our current remote (cloudflare) state match the desired state.

2021-11-02 16:30 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/cloudflare.go
> +			// unless the type is not A, AAAA, CNAME. Other types can be duplicated
Good point, CNAME is the only one that needs to be treated as a modify.

2021-11-02 16:33 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/cloudflare.go
> +			// unless the type is not A, AAAA, CNAME. Other types can be duplicated
Ah I see what I was doing here, I'll have to come back to this and add a bit more logic here. E.g. if we're moving from some CNAME with some dns name e.g. `a.example.com` to an A record with `a.example.com`, I don't think Cloudflare would be happy with that.

I might just instead expect the operator of this tool to handle this properly by putting exist=false on the CNAME type when moving to A records.

2021-11-02 16:35 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/cloudflare.go
> +			}
I'll test this behavior and write a comment what it does alongside adding some tests I think.

2021-11-02 18:28 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/cloudflare.go
> +	}
Yeah, I agree, But I think the users of the tool don't actually care what happens here? 

I'll probably revisit this in the future if we see the need to change this if that sounds good to you?

2021-11-02 18:29 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cmd/apply.go
> +		// todo(@aaomidi): We really need to make sure we're not passing in empty files.
https://github.com/letsencrypt/sre-tools/issues/43

2021-11-02 19:39 UTC, jsha commented on cmd/cloudflare-dns-handler/cloudflare/cloudflare.go
> +	}
Since you're including the body, and the body probably explains the problem in more detail, I think that's fine. One request: Try munging your auth token and running a request with this. Does the emitted error output look useful and informative?

2021-11-11 23:23 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/cloudflare.go
> +	}
```
2021/11/11 18:23:33 cloudflare api returned a 400 status: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null}
exit status 1

```

I'd say that's good enough

2021-11-11 23:36 UTC, aaomidi commented
Still working on some more things w/ this.

2021-11-18 20:32 UTC, pgporada commented on cmd/cloudflare-dns-handler/cloudflare/cloudflare.go
> +		time.Sleep(1 * time.Second)
Is this really needed? What happens without this?

2021-11-18 20:32 UTC, pgporada commented on cmd/cloudflare-dns-handler/cloudflare/modify.go
> +const modifyDNSRecord = "https://api.cloudflare.com/client/v4/zones/%s/dns_records/%s"
This exact URL is used several times throughout the script which I guess is fine, but is there a way to only define it once like have a file that provides

```
const {
    postDNSRecord = "https://api.cloudflare.com/client/v4/zones/%s/dns_records/%s"
    zoneRecord = "https://api.cloudflare.com/something"
}
```

2021-11-18 20:58 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/cloudflare.go
> +		time.Sleep(1 * time.Second)
> The Cloudflare API sets a maximum of 1,200 requests in a five minute period.

So, not really. Sometimes if you try to remove a record that was just added, cloudflare gets angry. I mainly added this so we have an opportunity to ctrl+c if we realize something is bad. But yeah, I'm fine removing this.

2021-11-18 21:02 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/modify.go
> +const modifyDNSRecord = "https://api.cloudflare.com/client/v4/zones/%s/dns_records/%s"
I don't think I've repeated this specific URL? Or do you mean have 

```
https://api.cloudflare.com/client/v4
```

Separate from:

```
/zones/%s/dns_records/%s"
```

2021-11-19 22:37 UTC, BranLwyd requested changes
initial pass -- almost all nits, a few Qs to help orient me on the problem domain

2021-11-19 22:37 UTC, BranLwyd commented on cmd/cloudflare-dns-handler/cloudflare/diff.go
> +func getActionToExist(zoneId string, diff *diff, want Record) ([]Action, error) {
nit: it looks like the returned `error` will always be nil. Drop it?

2021-11-19 22:37 UTC, BranLwyd commented on cmd/cloudflare-dns-handler/cloudflare/diff.go
> +		diff.cleanup()
Q: how many records will a typical zone have? `diff.cleanup` is `O(|diff|)`, and since it's called `O(|desired|)` times, this causes this code to be `O(n^2)` (since, typically, `|diff|` and `|desired|` will be around the same size). A linear-time implementation is possible, but may be overkill if you're managing just a few records.

2021-11-22 22:06 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/cloudflare.go
> +	err = pterm.DefaultTable.WithData(data).Render()
I'll try to find places where I've used this and change them!

2021-11-22 22:11 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/cloudflare.go
> +	if c.dryRun {
Hmm, that's a good idea. I'm going to make this into an issue and address it in the future.

2021-11-22 22:18 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/diff.go
> +func getActionToExist(zoneId string, diff *diff, want Record) ([]Action, error) {
I think this might get a bit more complex in the future, so let's keep this piped in for now. It's probably YAGNI, but I think it's generally harmless.

2021-11-22 22:18 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/diff.go
> +		diff.cleanup()
Yeah the performance doesn't matter that strongly here.

2021-11-22 23:21 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/create.go
> +	req, err := http.NewRequest("POST", fmt.Sprintf(createDNSRecord, zoneId), bytes.NewBuffer(data))
I'll address this in a future PR too.

2021-11-22 23:51 UTC, BranLwyd approved these changes
LGTM, nice work!

2021-11-22 23:56 UTC, pgporada commented on cmd/cloudflare-dns-handler/cloudflare/create.go
> +	req, err := http.NewRequest("POST", fmt.Sprintf(createDNSRecord, zoneId), bytes.NewBuffer(data))
@aaomidi Can you open an issue for this please?

2021-11-22 23:59 UTC, pgporada requested changes

2021-11-22 23:59 UTC, pgporada commented on cloudflare-dns-handler/README.md
> +1. Prepare a toml state file.
Can you provide an example toml file?

2021-11-23 02:07 UTC, jsha commented on cmd/cloudflare-dns-handler/cloudflare/cloudflare.go
> +	err = pterm.DefaultTable.WithData(data).Render()
FWIW, we recently discussed this in Boulder and came to the opposite conclusion: https://github.com/letsencrypt/boulder/pull/5752. It's not a super strong preference either way; as mentioned in the issue, there are a lot of both cases.

Part of the reasoning here: the one-line if check works fine for things that only return an error. But as soon as you return a successful value and an error, you have a scoping headache:

```
var foo Foo
var err error
if foo, err = doSomething(); err != nil {
  return err
}
... now we can do something with foo ...
```

Of course you can readily solve that by reserving the one-line style for functions that only return error, and using the two-line style for others:

```
foo, err := doSomething()
if err != nil {
  return err
}
```

But then some of your error checks look one way, and some look another; it breaks pattern matching somewhat.

In theory, downscoping as much as you can is great. In practice, I have never seen a bug caused by checking an error that wasn't in scope (I've seen a lot of bugs caused by failing to check an error, but that's not affected by this pattern).

2021-11-23 22:32 UTC, aaomidi commented on cloudflare-dns-handler/README.md
> +1. Prepare a toml state file.
https://github.com/letsencrypt/sre-tools/pull/38/commits/62cadd8c049258281418742e3546947e84c6329e

2021-11-23 22:53 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/modify.go
> +const modifyDNSRecord = "https://api.cloudflare.com/client/v4/zones/%s/dns_records/%s"
I couldn't find a good naming scheme that wouldn't confuse a reader coming back to this code, so I think some code duplication is probably okay here maybe.

2021-11-24 07:57 UTC, aaomidi commented on .github/workflows/test.yaml
> +    name: coverage and lint for cloudflare dns handler
I need to checkout the code here before this

2021-11-29 23:01 UTC, aaomidi commented on cmd/cloudflare-dns-handler/cloudflare/cloudflare.go
> +			}
Wrote some tests for the diffing behavior: https://github.com/letsencrypt/sre-tools/pull/38/commits/8478d6311cbeb33b64f9d38d2cf9e36edac8fdaf

2021-11-29 23:29 UTC, pgporada approved these changes
Looks good to me

2021-11-29 23:36 UTC, aaomidi commented
Dismissing @jsha's review per our conversation on Slack

2021-11-29 23:37 UTC, merged